let Source = Excel.CurrentWorkbook(){[Name="RawData"]}[Content], #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type date}, {"Column4", type number}}), #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Column1] <> null and [Column1] <> "")), #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Custom", each if [Column4] > 0 then "Active" else "Inactive"), #"Sorted Rows" = Table.Sort(#"Added Custom",{{"Column3", Order.Descending}}), #"Removed Duplicates" = Table.Distinct(#"Sorted Rows", {"Column1"}), #"Formatted Table" = Table.TransformColumnTypes(#"Removed Duplicates",{{"Column1", type text}, {"Column2", type text}, {"Column3", type date}, {"Column4", type number}, {"Custom", type text}}) in #"Formatted Table"